import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>Next Tailwind</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="flex flex-col items-center justify-center min-h-full py-16">
        <h2 className="text-5xl text-violet-700 font-semibold mb-12">
          Testing out Portable Text
        </h2>

        <p className="text-2xl">
          Go to the{" "}
          <a href="/blog" className="text-violet-600 font-bold">
            blog
          </a>{" "}
          page
        </p>
      </main>
    </div>
  );
}
